chore: more connection verification is needed, postgres cluster is booting up
chore: versions for release

diff --git a/helm/patroni-migration/templates/database-migration-job.yaml b/helm/patroni-migration/templates/database-migration-job.yaml
--- a/helm/patroni-migration/templates/database-migration-job.yaml
+++ b/helm/patroni-migration/templates/database-migration-job.yaml
@@ -106,7 +106,7 @@ spec:
             - "bin/bash"
             - "-c"
             - |
-              set -euxo pipefail;
+              set -euo pipefail;
 
               cd workspace
 
@@ -124,6 +124,15 @@ spec:
                 sleep 10;
               done;
 
+              table_count=$( \
+                PGHOST=$TARGET_SUPERUSER_PGHOST PGPORT=$TARGET_SUPERUSER_PGPORT PGUSER=$TARGET_SUPERUSER_PGUSER PGPASSWORD=$TARGET_SUPERUSER_PGPASSWORD \
+                psql -t --csv -d $SOURCE_PGDATABASE -c "select count(*) from pg_catalog.pg_tables where schemaname not in ('pg_catalog','information_schema');" \
+              );
+
+              if [[ $table_count != "0" ]] then
+                echo "Database $SOURCE_PGDATABASE is not empty in the target cluster, aborting to prevent accidental overwrite";
+                exit 1;
+              fi;
 
               # pgpass file
               echo "$SOURCE_PGHOST:$SOURCE_PGPORT:$SOURCE_PGDATABASE:$SOURCE_PGUSER:$SOURCE_PGPASSWORD" >> .pgpass
@@ -131,8 +140,6 @@ spec:
               echo "$TARGET_SUPERUSER_PGHOST:$TARGET_SUPERUSER_PGPORT:$SOURCE_PGDATABASE:$TARGET_SUPERUSER_PGUSER:$TARGET_SUPERUSER_PGPASSWORD" >> .pgpass
               
               chmod 0600 .pgpass
-
-              cat .pgpass
 
               export PGPASSFILE=".pgpass"
 
