chore: adding secret to notify of the migration success

diff --git a/helm/patroni-migration/templates/wait-for-databases-job.yaml b/helm/patroni-migration/templates/wait-for-databases-job.yaml
--- a/helm/patroni-migration/templates/wait-for-databases-job.yaml
+++ b/helm/patroni-migration/templates/wait-for-databases-job.yaml
@@ -103,6 +103,13 @@ spec:
             - |
               set -euo pipefail;
 
+              {{- $secretName := printf "%-%" (print (include "patroni-migration.fullname" .)) "migrated-secret" }}
+              {{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
+              {{- if $secret }}
+              echo "Database migration already executed, aborting to avoid overwriting data";
+              exit 1;
+              {{- end -}}
+
               until PGHOST=$SOURCE_PGHOST PGPORT=$SOURCE_PGPORT PGUSER=$SOURCE_PGUSER PGPASSWORD=$SOURCE_PGPASSWORD pg_isready;
               do
                 echo "Waiting for source database...(10s)";
@@ -114,11 +121,6 @@ spec:
                 echo "Waiting for target database...(10s)";
                 sleep 10;
               done;
-
-              if PGHOST=$TARGET_PGHOST PGPORT=$TARGET_PGPORT PGUSER=$TARGET_PGUSER PGPASSWORD=$TARGET_PGPASSWORD psql -lqt | cut -d \| -f 1 | grep -qw $SOURCE_PGDATABASE; then
-                echo "Database $SOURCE_PGDATABASE already exists on target, aborting to prevent accidental overwrite";
-                exit 1;
-              fi;
 
               echo "Databases at $SOURCE_PGHOST and $TARGET_PGHOST ready to start migration!"
 
