only alter roles on workers if citus is enabled

diff --git a/root/usr/bin/alter-role b/root/usr/bin/alter-role
--- a/root/usr/bin/alter-role
+++ b/root/usr/bin/alter-role
@@ -27,36 +27,30 @@ _psql() {
     PGOPTIONS='--client-min-messages=warning' psql -qtA --set ON_ERROR_STOP=1 "$@" 2>&1
 }
 
-echo "$user and $privilege"
-
 read -r -d '' alter_user_query<<EOF
 alter role $user $privilege;
 EOF
-read -r -d '' alter_user_query_workers<<EOF
-select nodename, success, result from run_command_on_workers('${alter_user_query//\'/\'\'}');
-EOF
 
-read -ra worker_nodes<<<"$(_psql -c 'select node_name from master_get_active_worker_nodes();')"
-
-read -r -d '' test_things<<EOF
-select
-EOF
-
-coordinator_out=$(_psql <<< "$alter_user_query")
+coordinator_out=$(_psql -c "$alter_user_query")
 if [[ $coordinator_out == ERROR* ]]; then
     echo "$coordinator_out"
     exit 1
 fi
 
-# Alter user on the workers
-mapfile -t alter_user_workers_out <<< "$(_psql <<< "$alter_user_query_workers")"
-for worker_out in "${alter_user_workers_out[@]}"
-do
-    IFS='|' read -ra worker_out_fields <<< "$worker_out"
-    if [ "${worker_out_fields[1]}" == "f" ]; then
-        echo "Error on worker ${worker_out_fields[0]}: ${worker_out_fields[2]}"
-        exit 1
-    fi
-done
+if [ "$(_psql -c "select count(*) from pg_extension where extname = 'citus';")" == "1" ]; then
+    # Alter user on the workers
+    read -r -d '' alter_user_query_workers<<EOF
+    select nodename, success, result from run_command_on_workers('${alter_user_query//\'/\'\'}');
+EOF
+    mapfile -t alter_user_workers_out <<< "$(_psql <<< "$alter_user_query_workers")"
+    for worker_out in "${alter_user_workers_out[@]}"
+    do
+        IFS='|' read -ra worker_out_fields <<< "$worker_out"
+        if [ "${worker_out_fields[1]}" == "f" ]; then
+            echo "Error on worker ${worker_out_fields[0]}: ${worker_out_fields[2]}"
+            exit 1
+        fi
+    done
+fi
 
 exit 0
