feature: rewrite create-user-db options and handle read-only users
BREAKING CHANGES: see the usage of create-user-db

diff --git a/root/usr/bin/create-user-db b/root/usr/bin/create-user-db
--- a/root/usr/bin/create-user-db
+++ b/root/usr/bin/create-user-db
@@ -5,29 +5,81 @@
 # Usage:
 # -----------------------------------------------------------------------------
 usage() {
-    cat << EOF
+  cat << EOF
 $0
 
 Creates a database and a user with the given password.
 Grants all privileges on the database to the created user.
 
-Usage: $0 USER DATABASE PASSWORD ENABLE_CITUS
+Usage: $0 --user USER --db DATABASE --password PASSWORD [--enable-citus] [--owner | --privileges PRIVILEGES --schemas SCHEMAS]
+
+Options:
+  -u, --user USER            the name of the user to create
+  -p, --password PASSWORD    the password for the new user
+  -d, --db DATABASE          the name of the database the user will have access to. If it does not exist, the database will be created
+  --owner                    set the newly created user as the database owner
+  --privileges PRIVILEGES    if they are not an owner, specifies a comma-separated list of privileges the user will have
+  --schemas SCHEMAS          if they are not an owner, specifies a comma-separated list of schemas where the privileges mentions above will be applied
+  --enable-citus             enables the Citus extension in the database, and creates the database and user in the Citus workers
+  -h, --help                 prints this help message
 EOF
-    exit 1
 }
 
-if [ "$#" -ne 3 ] && [ "$#" -ne 4 ]; then
-    echo "Passed $# parameters. Expected 3 or 4."
+user_is_owner=false
+enable_citus=false
+while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
+  -u | --user )
+    shift
+    user=$1
+    ;;
+  -d | --db )
+    shift
+    db=$1
+    ;;
+  -p | --password )
+    shift
+    password=$1
+    ;;
+  --owner )
+    user_is_owner=true
+    ;;
+  --enable-citus )
+    enable_citus=true
+    ;;
+  --privileges )
+    shift
+    IFS=',' read -r -a privileges <<< "$1"
+    ;;
+  --schemas )
+    shift
+    IFS=',' read -r -a schemas <<< "$1"
+    ;;
+  -h | --help )
     usage
+    exit 0
+    ;;
+esac; shift; done
+
+if [ -z  "$user" ]; then
+  echo "The --user parameter is required."
+  usage
+  exit 1
 fi
 
-password=$3
-user=$1
-db=$2
-enable_citus=${4:-false}
+if [ -z  "$password" ]; then
+  echo "The --password parameter is required."
+  usage
+  exit 1
+fi
+
+if [ -z  "$db" ]; then
+  echo "The --db parameter is required."
+  usage
+  exit 1
+fi
 
 _psql() {
-    PGOPTIONS='--client-min-messages=warning' psql -qtA --set ON_ERROR_STOP=1 "$@" 2>&1
+  PGOPTIONS='--client-min-messages=warning' psql -qtA --set ON_ERROR_STOP=1 "$@" 2>&1
 }
 
 create_db_query="create database $db;"
@@ -36,25 +88,35 @@ read -r -d '' create_user_query<<EOF
 create user $user with encrypted password '$password';
 revoke all on database $db from public;
 revoke all on database postgres from $user;
-grant all on database $db to $user;
-alter database $db owner to $user;
 EOF
+
+if $user_is_owner; then
+  create_user_query+="grant all on database $db to $user; alter database $db owner to $user;"
+else
+  create_user_query+="grant connect on database $db to $user;"
+  for schema in "${schemas[@]}"
+  do
+    create_user_query+="grant usage on schema $schema to $user;"
+    create_user_query+="grant ${privileges[*]} on all tables in schema $schema to $user;"
+    create_user_query+="alter default privileges in schema $schema grant ${privileges[*]} on tables to $user;"
+  done
+fi
 
 # Create DB on the coordinator
 coordinator_out=$(_psql -c "$create_db_query")
 if [ "$coordinator_out" == "ERROR:  database \"$db\" already exists" ]; then
-    echo "Database \"$db\" already exists on coordinator node"
+  echo "Database \"$db\" already exists on coordinator node"
 elif [[ $coordinator_out == ERROR* ]]; then
-    echo "$coordinator_out"
-    exit 1
+  echo "$coordinator_out"
+  exit 1
 fi
 
 coordinator_out=$(_psql <<< "$create_user_query")
 if [ "$coordinator_out" == "ERROR:  role \"$user\" already exists" ]; then
-    echo "User \"$user\" already exists on coordinator node"
+  echo "User \"$user\" already exists on coordinator node"
 elif [[ $coordinator_out == ERROR* ]]; then
-    echo "$coordinator_out"
-    exit 1
+  echo "$coordinator_out"
+  exit 1
 fi
 
 if $enable_citus; then
