create-user-db is idempotent

diff --git a/root/usr/bin/create-user-db b/root/usr/bin/create-user-db
--- a/root/usr/bin/create-user-db
+++ b/root/usr/bin/create-user-db
@@ -41,19 +41,71 @@ escaped_create_user_query="${create_user_query//\'/\'\'}"
 
 read -ra worker_nodes<<<"$(_psql -c 'select node_name from master_get_active_worker_nodes();')"
 
-_psql << EOF
-    $create_db_query
-    select run_command_on_workers('$create_db_query');
-EOF
+# Create DB on the coordinator
+coordinator_out=$(_psql -c "$create_db_query")
+if [ "$coordinator_out" == "ERROR:  database \"$db\" already exists" ]; then
+    echo "Database \"$db\" already exists on coordinator node"
+elif [[ $coordinator_out == ERROR* ]]; then
+    echo "$coordinator_out"
+    exit 1
+fi
 
-_psql << EOF
-    $create_user_query
-    select run_command_on_workers('$escaped_create_user_query');
-EOF
+# Create DB on the workers
+read -ra create_db_workers_out<<<"$(_psql -c "select nodename, success, result from run_command_on_workers(\'$create_db_query\');")"
+for worker_out in "${create_db_workers_out[@]}"
+do
+    IFS='|' read -r -a worker_out_fields <<< "$worker_out"
+    if [ "${worker_out_fields[1]}" == "f" ]; then
+        if [ "${worker_out_fields[1]}" == "ERROR:  database \"$db\" already exists" ]; then
+            echo "Database \"$db\" already exists on worker node ${worker_out_fields[0]}"
+        else
+            echo "Error on worker ${worker_out_fields[0]}: ${worker_out_fields[1]}"
+            exit 1
+        fi
+    fi
+done
 
-_psql -d "$db" -c "create extension citus;"
+# Register the workers in the newly created DB
+for worker_node in "${worker_nodes[@]}"
+do
+ _psql -d "$db" -c "select master_add_node('$worker_node', 5432);"
+done
+
+
+coordinator_out=$(_psql -c "$create_user_query")
+if [ "$coordinator_out" == "ERROR:  role \"$user\" already exists" ]; then
+    echo "User \"$user\" already exists on coordinator node"
+elif [[ $coordinator_out == ERROR* ]]; then
+    echo "$coordinator_out"
+    exit 1
+fi
+
+# Create user on the workers
+read -ra create_db_workers_out<<<"$(_psql -c "select nodename, success, result from run_command_on_workers(\'$escaped_create_user_query\')")"
+for worker_out in "${create_db_workers_out[@]}"
+do
+    IFS='|' read -r -a worker_out_fields <<< "$worker_out"
+    if [ "${worker_out_fields[1]}" == "f" ]; then
+        if [ "${worker_out_fields[1]}" == "ERROR:  role \"$user\" already exists" ]; then
+            echo "User \"$user\" already exists on worker node ${worker_out_fields[0]}"
+        else
+            echo "Error on worker ${worker_out_fields[0]}: ${worker_out_fields[1]}"
+            exit 1
+        fi
+    fi
+done
+
+coordinator_out=$(_psql -d "$db" -c "create extension citus;")
+if [ "$coordinator_out" == "ERROR:  extension \"citus\" already exists" ]; then
+    echo "Extension citus already exists on coordinator node"
+elif [[ $coordinator_out == ERROR* ]]; then
+    echo "$coordinator_out"
+    exit 1
+fi
 
 for worker_node in "${worker_nodes[@]}"
 do
  _psql -d "$db" -c "select master_add_node('$worker_node', 5432);"
 done
+
+exit 0
